[package]
name = "dcmprs"
version = "0.1.0"
edition = "2021"

[dependencies]
zstd = "0.13"
tempfile = "3.0"
env_logger = "0.10"
log = "0.4"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
